/********************************************************************************
** Form generated from reading ui file 'mainwindow.ui'
**
** Created: Sat Jul 12 22:24:29 2008
**      by: Qt User Interface Compiler version 4.4.0
**
** WARNING! All changes made in this file will be lost when recompiling ui file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QToolBar>
#include <QtGui/QWidget>

namespace Ui {

class Ui_MainWindow
{
public:
    QAction *open_file_action;
    QAction *play_forward_action;
    QAction *play_backward_action;
    QAction *audio_volume_up_action;
    QAction *audio_volume_down_action;
    QAction *video_fullscreen_action;
    QAction *play_forward_more_action;
    QAction *play_backward_more_action;
    QAction *play_pause_action;
    QAction *file_exit_action;
    QAction *play_stop_action;
    QAction *play_previous_action;
    QAction *play_next_action;
    QAction *audio_mute_action;
    QAction *video_aspect_auto_action;
    QAction *video_aspect_widget_action;
    QAction *video_aspect_4_3_action;
    QAction *video_aspect_16_9_action;
    QAction *video_equalizer_action;
    QAction *play_show_playlist_action;
    QAction *subtitle_step_up_action;
    QAction *subtitle_step_down_action;
    QAction *subtitle_add_action;
    QAction *subtitle_disable_action;
    QAction *subtitle_clear_action;
    QAction *video_size_100_action;
    QAction *video_size_200_action;
    QAction *video_size_50_action;
    QAction *video_size_300_action;
    QAction *video_size_400_action;
    QAction *subtitle_sync_increase_action;
    QAction *subtitle_sync_decrease_action;
    QAction *subtitle_sync_current_action;
    QAction *option_preferences_action;
    QAction *video_size_150_action;
    QAction *video_size_250_action;
    QAction *video_size_350_action;
    QAction *video_crop_off_action;
    QAction *video_crop_4_3_action;
    QAction *video_crop_16_9_action;
    QAction *video_size_user_action;
    QAction *action_6;
    QAction *video_on_top_always_action;
    QAction *video_on_top_only_playing_action;
    QAction *video_on_top_off_action;
    QAction *about_qt_action;
    QAction *about_cmp_action;
    QAction *play_ab_select_action;
    QAction *play_ab_advance_action;
    QAction *play_ab_stop_action;
    QAction *play_forward_much_more_action;
    QAction *play_backward_much_more_action;
    QAction *video_aspect_2_35_1_action;
    QAction *video_crop_2_35_1_action;
    QAction *play_speed_current_action;
    QAction *play_speed_increase_action;
    QAction *play_speed_decrease_action;
    QAction *play_speed_restore_action;
    QAction *play_speed_double_action;
    QAction *play_speed_half_action;
    QAction *action_2;
    QAction *open_url_action;
    QAction *open_dvd_action;
    QAction *recent_clear_action;
    QAction *action_3;
    QAction *action1;
    QWidget *centralwidget;
    QMenuBar *menubar;
    QMenu *file_menu;
    QMenu *file_open_menu;
    QMenu *open_recent_menu;
    QMenu *play_menu;
    QMenu *play_ab_menu;
    QMenu *play_speed_menu;
    QMenu *seek_dvd_menu;
    QMenu *seek_title_menu;
    QMenu *seek_chapter_menu;
    QMenu *video_menu;
    QMenu *video_aspect_menu;
    QMenu *video_size_menu;
    QMenu *video_crop_menu;
    QMenu *video_on_top_menu;
    QMenu *audio_menu;
    QMenu *subtitle_menu;
    QMenu *subtitle_select_menu;
    QMenu *subtitle_sync_menu;
    QMenu *subtitle_pos_menu;
    QMenu *option_menu;
    QMenu *help_menu;
    QToolBar *play_bar;

    void setupUi(QMainWindow *Ui__MainWindow)
    {
    if (Ui__MainWindow->objectName().isEmpty())
        Ui__MainWindow->setObjectName(QString::fromUtf8("Ui__MainWindow"));
    Ui__MainWindow->setEnabled(true);
    Ui__MainWindow->resize(576, 600);
    open_file_action = new QAction(Ui__MainWindow);
    open_file_action->setObjectName(QString::fromUtf8("open_file_action"));
    QIcon icon;
    icon.addPixmap(QPixmap(QString::fromUtf8(":/img/document-open.png")), QIcon::Normal, QIcon::Off);
    open_file_action->setIcon(icon);
    play_forward_action = new QAction(Ui__MainWindow);
    play_forward_action->setObjectName(QString::fromUtf8("play_forward_action"));
    QIcon icon1;
    icon1.addPixmap(QPixmap(QString::fromUtf8(":/img/media-seek-forward.png")), QIcon::Normal, QIcon::Off);
    play_forward_action->setIcon(icon1);
    play_forward_action->setShortcutContext(Qt::ApplicationShortcut);
    play_backward_action = new QAction(Ui__MainWindow);
    play_backward_action->setObjectName(QString::fromUtf8("play_backward_action"));
    QIcon icon2;
    icon2.addPixmap(QPixmap(QString::fromUtf8(":/img/media-seek-backward.png")), QIcon::Normal, QIcon::Off);
    play_backward_action->setIcon(icon2);
    audio_volume_up_action = new QAction(Ui__MainWindow);
    audio_volume_up_action->setObjectName(QString::fromUtf8("audio_volume_up_action"));
    audio_volume_down_action = new QAction(Ui__MainWindow);
    audio_volume_down_action->setObjectName(QString::fromUtf8("audio_volume_down_action"));
    video_fullscreen_action = new QAction(Ui__MainWindow);
    video_fullscreen_action->setObjectName(QString::fromUtf8("video_fullscreen_action"));
    video_fullscreen_action->setCheckable(true);
    QIcon icon3;
    icon3.addPixmap(QPixmap(QString::fromUtf8(":/img/view-fullscreen.png")), QIcon::Normal, QIcon::Off);
    video_fullscreen_action->setIcon(icon3);
    play_forward_more_action = new QAction(Ui__MainWindow);
    play_forward_more_action->setObjectName(QString::fromUtf8("play_forward_more_action"));
    play_backward_more_action = new QAction(Ui__MainWindow);
    play_backward_more_action->setObjectName(QString::fromUtf8("play_backward_more_action"));
    play_pause_action = new QAction(Ui__MainWindow);
    play_pause_action->setObjectName(QString::fromUtf8("play_pause_action"));
    QIcon icon4;
    icon4.addPixmap(QPixmap(QString::fromUtf8(":/img/media-playback-start.png")), QIcon::Normal, QIcon::Off);
    play_pause_action->setIcon(icon4);
    file_exit_action = new QAction(Ui__MainWindow);
    file_exit_action->setObjectName(QString::fromUtf8("file_exit_action"));
    QIcon icon5;
    icon5.addPixmap(QPixmap(QString::fromUtf8(":/img/application-exit.png")), QIcon::Normal, QIcon::Off);
    file_exit_action->setIcon(icon5);
    play_stop_action = new QAction(Ui__MainWindow);
    play_stop_action->setObjectName(QString::fromUtf8("play_stop_action"));
    QIcon icon6;
    icon6.addPixmap(QPixmap(QString::fromUtf8(":/img/media-playback-stop.png")), QIcon::Normal, QIcon::Off);
    play_stop_action->setIcon(icon6);
    play_previous_action = new QAction(Ui__MainWindow);
    play_previous_action->setObjectName(QString::fromUtf8("play_previous_action"));
    QIcon icon7;
    icon7.addPixmap(QPixmap(QString::fromUtf8(":/img/media-skip-backward.png")), QIcon::Normal, QIcon::Off);
    play_previous_action->setIcon(icon7);
    play_next_action = new QAction(Ui__MainWindow);
    play_next_action->setObjectName(QString::fromUtf8("play_next_action"));
    QIcon icon8;
    icon8.addPixmap(QPixmap(QString::fromUtf8(":/img/media-skip-forward.png")), QIcon::Normal, QIcon::Off);
    play_next_action->setIcon(icon8);
    audio_mute_action = new QAction(Ui__MainWindow);
    audio_mute_action->setObjectName(QString::fromUtf8("audio_mute_action"));
    audio_mute_action->setCheckable(true);
    QIcon icon9;
    icon9.addPixmap(QPixmap(QString::fromUtf8(":/img/player-volume.png")), QIcon::Normal, QIcon::Off);
    audio_mute_action->setIcon(icon9);
    video_aspect_auto_action = new QAction(Ui__MainWindow);
    video_aspect_auto_action->setObjectName(QString::fromUtf8("video_aspect_auto_action"));
    video_aspect_auto_action->setCheckable(true);
    video_aspect_auto_action->setChecked(true);
    video_aspect_widget_action = new QAction(Ui__MainWindow);
    video_aspect_widget_action->setObjectName(QString::fromUtf8("video_aspect_widget_action"));
    video_aspect_widget_action->setCheckable(true);
    video_aspect_4_3_action = new QAction(Ui__MainWindow);
    video_aspect_4_3_action->setObjectName(QString::fromUtf8("video_aspect_4_3_action"));
    video_aspect_4_3_action->setCheckable(true);
    video_aspect_16_9_action = new QAction(Ui__MainWindow);
    video_aspect_16_9_action->setObjectName(QString::fromUtf8("video_aspect_16_9_action"));
    video_aspect_16_9_action->setCheckable(true);
    video_equalizer_action = new QAction(Ui__MainWindow);
    video_equalizer_action->setObjectName(QString::fromUtf8("video_equalizer_action"));
    QIcon icon10;
    icon10.addPixmap(QPixmap(QString::fromUtf8(":/img/view-media-equalizer.png")), QIcon::Normal, QIcon::Off);
    video_equalizer_action->setIcon(icon10);
    play_show_playlist_action = new QAction(Ui__MainWindow);
    play_show_playlist_action->setObjectName(QString::fromUtf8("play_show_playlist_action"));
    play_show_playlist_action->setCheckable(false);
    QIcon icon11;
    icon11.addPixmap(QPixmap(QString::fromUtf8(":/img/view-media-playlist.png")), QIcon::Normal, QIcon::Off);
    play_show_playlist_action->setIcon(icon11);
    subtitle_step_up_action = new QAction(Ui__MainWindow);
    subtitle_step_up_action->setObjectName(QString::fromUtf8("subtitle_step_up_action"));
    subtitle_step_down_action = new QAction(Ui__MainWindow);
    subtitle_step_down_action->setObjectName(QString::fromUtf8("subtitle_step_down_action"));
    subtitle_add_action = new QAction(Ui__MainWindow);
    subtitle_add_action->setObjectName(QString::fromUtf8("subtitle_add_action"));
    subtitle_disable_action = new QAction(Ui__MainWindow);
    subtitle_disable_action->setObjectName(QString::fromUtf8("subtitle_disable_action"));
    subtitle_disable_action->setCheckable(true);
    subtitle_disable_action->setChecked(true);
    subtitle_disable_action->setVisible(false);
    subtitle_clear_action = new QAction(Ui__MainWindow);
    subtitle_clear_action->setObjectName(QString::fromUtf8("subtitle_clear_action"));
    subtitle_clear_action->setEnabled(false);
    video_size_100_action = new QAction(Ui__MainWindow);
    video_size_100_action->setObjectName(QString::fromUtf8("video_size_100_action"));
    video_size_100_action->setCheckable(true);
    video_size_200_action = new QAction(Ui__MainWindow);
    video_size_200_action->setObjectName(QString::fromUtf8("video_size_200_action"));
    video_size_200_action->setCheckable(true);
    video_size_50_action = new QAction(Ui__MainWindow);
    video_size_50_action->setObjectName(QString::fromUtf8("video_size_50_action"));
    video_size_50_action->setCheckable(true);
    video_size_300_action = new QAction(Ui__MainWindow);
    video_size_300_action->setObjectName(QString::fromUtf8("video_size_300_action"));
    video_size_300_action->setCheckable(true);
    video_size_400_action = new QAction(Ui__MainWindow);
    video_size_400_action->setObjectName(QString::fromUtf8("video_size_400_action"));
    video_size_400_action->setCheckable(true);
    subtitle_sync_increase_action = new QAction(Ui__MainWindow);
    subtitle_sync_increase_action->setObjectName(QString::fromUtf8("subtitle_sync_increase_action"));
    subtitle_sync_decrease_action = new QAction(Ui__MainWindow);
    subtitle_sync_decrease_action->setObjectName(QString::fromUtf8("subtitle_sync_decrease_action"));
    subtitle_sync_current_action = new QAction(Ui__MainWindow);
    subtitle_sync_current_action->setObjectName(QString::fromUtf8("subtitle_sync_current_action"));
    option_preferences_action = new QAction(Ui__MainWindow);
    option_preferences_action->setObjectName(QString::fromUtf8("option_preferences_action"));
    QIcon icon12;
    icon12.addPixmap(QPixmap(QString::fromUtf8(":/img/preferences-system.png")), QIcon::Normal, QIcon::Off);
    option_preferences_action->setIcon(icon12);
    video_size_150_action = new QAction(Ui__MainWindow);
    video_size_150_action->setObjectName(QString::fromUtf8("video_size_150_action"));
    video_size_150_action->setCheckable(true);
    video_size_250_action = new QAction(Ui__MainWindow);
    video_size_250_action->setObjectName(QString::fromUtf8("video_size_250_action"));
    video_size_250_action->setCheckable(true);
    video_size_350_action = new QAction(Ui__MainWindow);
    video_size_350_action->setObjectName(QString::fromUtf8("video_size_350_action"));
    video_size_350_action->setCheckable(true);
    video_crop_off_action = new QAction(Ui__MainWindow);
    video_crop_off_action->setObjectName(QString::fromUtf8("video_crop_off_action"));
    video_crop_off_action->setCheckable(true);
    video_crop_off_action->setChecked(true);
    video_crop_4_3_action = new QAction(Ui__MainWindow);
    video_crop_4_3_action->setObjectName(QString::fromUtf8("video_crop_4_3_action"));
    video_crop_4_3_action->setCheckable(true);
    video_crop_16_9_action = new QAction(Ui__MainWindow);
    video_crop_16_9_action->setObjectName(QString::fromUtf8("video_crop_16_9_action"));
    video_crop_16_9_action->setCheckable(true);
    video_size_user_action = new QAction(Ui__MainWindow);
    video_size_user_action->setObjectName(QString::fromUtf8("video_size_user_action"));
    video_size_user_action->setCheckable(true);
    video_size_user_action->setChecked(true);
    action_6 = new QAction(Ui__MainWindow);
    action_6->setObjectName(QString::fromUtf8("action_6"));
    video_on_top_always_action = new QAction(Ui__MainWindow);
    video_on_top_always_action->setObjectName(QString::fromUtf8("video_on_top_always_action"));
    video_on_top_always_action->setCheckable(true);
    video_on_top_only_playing_action = new QAction(Ui__MainWindow);
    video_on_top_only_playing_action->setObjectName(QString::fromUtf8("video_on_top_only_playing_action"));
    video_on_top_only_playing_action->setCheckable(true);
    video_on_top_off_action = new QAction(Ui__MainWindow);
    video_on_top_off_action->setObjectName(QString::fromUtf8("video_on_top_off_action"));
    video_on_top_off_action->setCheckable(true);
    video_on_top_off_action->setChecked(true);
    about_qt_action = new QAction(Ui__MainWindow);
    about_qt_action->setObjectName(QString::fromUtf8("about_qt_action"));
    about_cmp_action = new QAction(Ui__MainWindow);
    about_cmp_action->setObjectName(QString::fromUtf8("about_cmp_action"));
    play_ab_select_action = new QAction(Ui__MainWindow);
    play_ab_select_action->setObjectName(QString::fromUtf8("play_ab_select_action"));
    play_ab_select_action->setCheckable(false);
    play_ab_advance_action = new QAction(Ui__MainWindow);
    play_ab_advance_action->setObjectName(QString::fromUtf8("play_ab_advance_action"));
    play_ab_stop_action = new QAction(Ui__MainWindow);
    play_ab_stop_action->setObjectName(QString::fromUtf8("play_ab_stop_action"));
    play_forward_much_more_action = new QAction(Ui__MainWindow);
    play_forward_much_more_action->setObjectName(QString::fromUtf8("play_forward_much_more_action"));
    play_backward_much_more_action = new QAction(Ui__MainWindow);
    play_backward_much_more_action->setObjectName(QString::fromUtf8("play_backward_much_more_action"));
    video_aspect_2_35_1_action = new QAction(Ui__MainWindow);
    video_aspect_2_35_1_action->setObjectName(QString::fromUtf8("video_aspect_2_35_1_action"));
    video_aspect_2_35_1_action->setCheckable(true);
    video_crop_2_35_1_action = new QAction(Ui__MainWindow);
    video_crop_2_35_1_action->setObjectName(QString::fromUtf8("video_crop_2_35_1_action"));
    video_crop_2_35_1_action->setCheckable(true);
    play_speed_current_action = new QAction(Ui__MainWindow);
    play_speed_current_action->setObjectName(QString::fromUtf8("play_speed_current_action"));
    play_speed_increase_action = new QAction(Ui__MainWindow);
    play_speed_increase_action->setObjectName(QString::fromUtf8("play_speed_increase_action"));
    play_speed_decrease_action = new QAction(Ui__MainWindow);
    play_speed_decrease_action->setObjectName(QString::fromUtf8("play_speed_decrease_action"));
    play_speed_restore_action = new QAction(Ui__MainWindow);
    play_speed_restore_action->setObjectName(QString::fromUtf8("play_speed_restore_action"));
    play_speed_double_action = new QAction(Ui__MainWindow);
    play_speed_double_action->setObjectName(QString::fromUtf8("play_speed_double_action"));
    play_speed_half_action = new QAction(Ui__MainWindow);
    play_speed_half_action->setObjectName(QString::fromUtf8("play_speed_half_action"));
    action_2 = new QAction(Ui__MainWindow);
    action_2->setObjectName(QString::fromUtf8("action_2"));
    open_url_action = new QAction(Ui__MainWindow);
    open_url_action->setObjectName(QString::fromUtf8("open_url_action"));
    open_dvd_action = new QAction(Ui__MainWindow);
    open_dvd_action->setObjectName(QString::fromUtf8("open_dvd_action"));
    recent_clear_action = new QAction(Ui__MainWindow);
    recent_clear_action->setObjectName(QString::fromUtf8("recent_clear_action"));
    action_3 = new QAction(Ui__MainWindow);
    action_3->setObjectName(QString::fromUtf8("action_3"));
    action1 = new QAction(Ui__MainWindow);
    action1->setObjectName(QString::fromUtf8("action1"));
    centralwidget = new QWidget(Ui__MainWindow);
    centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
    centralwidget->setGeometry(QRect(0, 25, 576, 563));
    Ui__MainWindow->setCentralWidget(centralwidget);
    menubar = new QMenuBar(Ui__MainWindow);
    menubar->setObjectName(QString::fromUtf8("menubar"));
    menubar->setGeometry(QRect(0, 0, 576, 25));
    menubar->setDefaultUp(false);
    file_menu = new QMenu(menubar);
    file_menu->setObjectName(QString::fromUtf8("file_menu"));
    file_open_menu = new QMenu(file_menu);
    file_open_menu->setObjectName(QString::fromUtf8("file_open_menu"));
    open_recent_menu = new QMenu(file_open_menu);
    open_recent_menu->setObjectName(QString::fromUtf8("open_recent_menu"));
    play_menu = new QMenu(menubar);
    play_menu->setObjectName(QString::fromUtf8("play_menu"));
    play_ab_menu = new QMenu(play_menu);
    play_ab_menu->setObjectName(QString::fromUtf8("play_ab_menu"));
    play_speed_menu = new QMenu(play_menu);
    play_speed_menu->setObjectName(QString::fromUtf8("play_speed_menu"));
    seek_dvd_menu = new QMenu(play_menu);
    seek_dvd_menu->setObjectName(QString::fromUtf8("seek_dvd_menu"));
    seek_title_menu = new QMenu(seek_dvd_menu);
    seek_title_menu->setObjectName(QString::fromUtf8("seek_title_menu"));
    seek_chapter_menu = new QMenu(seek_dvd_menu);
    seek_chapter_menu->setObjectName(QString::fromUtf8("seek_chapter_menu"));
    video_menu = new QMenu(menubar);
    video_menu->setObjectName(QString::fromUtf8("video_menu"));
    video_menu->setEnabled(true);
    video_aspect_menu = new QMenu(video_menu);
    video_aspect_menu->setObjectName(QString::fromUtf8("video_aspect_menu"));
    video_size_menu = new QMenu(video_menu);
    video_size_menu->setObjectName(QString::fromUtf8("video_size_menu"));
    video_crop_menu = new QMenu(video_menu);
    video_crop_menu->setObjectName(QString::fromUtf8("video_crop_menu"));
    video_on_top_menu = new QMenu(video_menu);
    video_on_top_menu->setObjectName(QString::fromUtf8("video_on_top_menu"));
    QIcon icon13;
    icon13.addPixmap(QPixmap(QString::fromUtf8(":/img/go-top.png")), QIcon::Normal, QIcon::Off);
    video_on_top_menu->setIcon(icon13);
    audio_menu = new QMenu(menubar);
    audio_menu->setObjectName(QString::fromUtf8("audio_menu"));
    subtitle_menu = new QMenu(menubar);
    subtitle_menu->setObjectName(QString::fromUtf8("subtitle_menu"));
    subtitle_select_menu = new QMenu(subtitle_menu);
    subtitle_select_menu->setObjectName(QString::fromUtf8("subtitle_select_menu"));
    QIcon icon14;
    icon14.addPixmap(QPixmap(QString::fromUtf8(":/img/format-justify-center.png")), QIcon::Normal, QIcon::Off);
    subtitle_select_menu->setIcon(icon14);
    subtitle_sync_menu = new QMenu(subtitle_menu);
    subtitle_sync_menu->setObjectName(QString::fromUtf8("subtitle_sync_menu"));
    subtitle_pos_menu = new QMenu(subtitle_menu);
    subtitle_pos_menu->setObjectName(QString::fromUtf8("subtitle_pos_menu"));
    option_menu = new QMenu(menubar);
    option_menu->setObjectName(QString::fromUtf8("option_menu"));
    help_menu = new QMenu(menubar);
    help_menu->setObjectName(QString::fromUtf8("help_menu"));
    Ui__MainWindow->setMenuBar(menubar);
    play_bar = new QToolBar(Ui__MainWindow);
    play_bar->setObjectName(QString::fromUtf8("play_bar"));
    play_bar->setGeometry(QRect(0, 588, 576, 12));
    play_bar->setMovable(false);
    play_bar->setAllowedAreas(Qt::BottomToolBarArea);
    play_bar->setIconSize(QSize(16, 16));
    Ui__MainWindow->addToolBar(Qt::BottomToolBarArea, play_bar);

    menubar->addAction(file_menu->menuAction());
    menubar->addAction(play_menu->menuAction());
    menubar->addAction(video_menu->menuAction());
    menubar->addAction(audio_menu->menuAction());
    menubar->addAction(subtitle_menu->menuAction());
    menubar->addAction(option_menu->menuAction());
    menubar->addAction(help_menu->menuAction());
    file_menu->addAction(file_open_menu->menuAction());
    file_menu->addSeparator();
    file_menu->addAction(file_exit_action);
    file_open_menu->addAction(open_file_action);
    file_open_menu->addAction(open_dvd_action);
    file_open_menu->addSeparator();
    file_open_menu->addAction(open_recent_menu->menuAction());
    open_recent_menu->addSeparator();
    open_recent_menu->addAction(recent_clear_action);
    play_menu->addAction(play_show_playlist_action);
    play_menu->addAction(play_speed_menu->menuAction());
    play_menu->addAction(play_ab_menu->menuAction());
    play_menu->addAction(seek_dvd_menu->menuAction());
    play_menu->addSeparator();
    play_menu->addAction(play_pause_action);
    play_menu->addAction(play_stop_action);
    play_menu->addAction(play_previous_action);
    play_menu->addAction(play_next_action);
    play_menu->addAction(play_backward_action);
    play_menu->addAction(play_backward_more_action);
    play_menu->addAction(play_backward_much_more_action);
    play_menu->addAction(play_forward_action);
    play_menu->addAction(play_forward_more_action);
    play_menu->addAction(play_forward_much_more_action);
    play_ab_menu->addAction(play_ab_select_action);
    play_ab_menu->addAction(play_ab_stop_action);
    play_ab_menu->addAction(play_ab_advance_action);
    play_speed_menu->addAction(play_speed_current_action);
    play_speed_menu->addSeparator();
    play_speed_menu->addAction(play_speed_double_action);
    play_speed_menu->addAction(play_speed_half_action);
    play_speed_menu->addAction(play_speed_increase_action);
    play_speed_menu->addAction(play_speed_decrease_action);
    play_speed_menu->addAction(play_speed_restore_action);
    seek_dvd_menu->addAction(seek_title_menu->menuAction());
    seek_dvd_menu->addAction(seek_chapter_menu->menuAction());
    video_menu->addAction(video_fullscreen_action);
    video_menu->addAction(video_on_top_menu->menuAction());
    video_menu->addSeparator();
    video_menu->addAction(video_size_menu->menuAction());
    video_menu->addAction(video_aspect_menu->menuAction());
    video_menu->addAction(video_crop_menu->menuAction());
    video_menu->addAction(video_equalizer_action);
    video_aspect_menu->addAction(video_aspect_auto_action);
    video_aspect_menu->addAction(video_aspect_widget_action);
    video_aspect_menu->addAction(video_aspect_4_3_action);
    video_aspect_menu->addAction(video_aspect_16_9_action);
    video_aspect_menu->addAction(video_aspect_2_35_1_action);
    video_size_menu->addAction(video_size_50_action);
    video_size_menu->addAction(video_size_100_action);
    video_size_menu->addAction(video_size_150_action);
    video_size_menu->addAction(video_size_200_action);
    video_size_menu->addAction(video_size_250_action);
    video_size_menu->addAction(video_size_300_action);
    video_size_menu->addAction(video_size_350_action);
    video_size_menu->addAction(video_size_400_action);
    video_size_menu->addAction(video_size_user_action);
    video_crop_menu->addAction(video_crop_off_action);
    video_crop_menu->addAction(video_crop_4_3_action);
    video_crop_menu->addAction(video_crop_16_9_action);
    video_crop_menu->addAction(video_crop_2_35_1_action);
    video_on_top_menu->addAction(video_on_top_always_action);
    video_on_top_menu->addAction(video_on_top_only_playing_action);
    video_on_top_menu->addAction(video_on_top_off_action);
    audio_menu->addAction(audio_volume_up_action);
    audio_menu->addAction(audio_volume_down_action);
    audio_menu->addAction(audio_mute_action);
    subtitle_menu->addAction(subtitle_select_menu->menuAction());
    subtitle_menu->addAction(subtitle_add_action);
    subtitle_menu->addAction(subtitle_pos_menu->menuAction());
    subtitle_menu->addAction(subtitle_sync_menu->menuAction());
    subtitle_select_menu->addAction(subtitle_clear_action);
    subtitle_select_menu->addSeparator();
    subtitle_select_menu->addAction(subtitle_disable_action);
    subtitle_sync_menu->addAction(subtitle_sync_current_action);
    subtitle_sync_menu->addSeparator();
    subtitle_sync_menu->addAction(subtitle_sync_increase_action);
    subtitle_sync_menu->addAction(subtitle_sync_decrease_action);
    subtitle_pos_menu->addAction(subtitle_step_up_action);
    subtitle_pos_menu->addAction(subtitle_step_down_action);
    option_menu->addAction(option_preferences_action);
    help_menu->addAction(about_qt_action);
    help_menu->addAction(about_cmp_action);

    retranslateUi(Ui__MainWindow);
    QObject::connect(subtitle_disable_action, SIGNAL(toggled(bool)), subtitle_disable_action, SLOT(setDisabled(bool)));

    QMetaObject::connectSlotsByName(Ui__MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *Ui__MainWindow)
    {
    Ui__MainWindow->setWindowTitle(QApplication::translate("Ui::MainWindow", "MainWindow", 0, QApplication::UnicodeUTF8));
    open_file_action->setText(QApplication::translate("Ui::MainWindow", "\355\214\214\354\235\274", 0, QApplication::UnicodeUTF8));
    open_file_action->setShortcut(QApplication::translate("Ui::MainWindow", "Ctrl+O", 0, QApplication::UnicodeUTF8));
    play_forward_action->setText(QApplication::translate("Ui::MainWindow", "\354\225\236\354\234\274\353\241\234", 0, QApplication::UnicodeUTF8));
    play_forward_action->setShortcut(QApplication::translate("Ui::MainWindow", "Right", 0, QApplication::UnicodeUTF8));
    play_backward_action->setText(QApplication::translate("Ui::MainWindow", "\353\222\244\353\241\234", 0, QApplication::UnicodeUTF8));
    play_backward_action->setShortcut(QApplication::translate("Ui::MainWindow", "Left", 0, QApplication::UnicodeUTF8));
    audio_volume_up_action->setText(QApplication::translate("Ui::MainWindow", "\354\206\214\353\246\254\355\201\254\352\262\214", 0, QApplication::UnicodeUTF8));
    audio_volume_up_action->setShortcut(QApplication::translate("Ui::MainWindow", "Up", 0, QApplication::UnicodeUTF8));
    audio_volume_down_action->setText(QApplication::translate("Ui::MainWindow", "\354\206\214\353\246\254\354\236\221\352\262\214", 0, QApplication::UnicodeUTF8));
    audio_volume_down_action->setShortcut(QApplication::translate("Ui::MainWindow", "Down", 0, QApplication::UnicodeUTF8));
    video_fullscreen_action->setText(QApplication::translate("Ui::MainWindow", "\354\240\204\354\262\264\355\231\224\353\251\264", 0, QApplication::UnicodeUTF8));
    video_fullscreen_action->setShortcut(QApplication::translate("Ui::MainWindow", "Return", 0, QApplication::UnicodeUTF8));
    play_forward_more_action->setText(QApplication::translate("Ui::MainWindow", "\353\247\216\354\235\264 \354\225\236\354\234\274\353\241\234", 0, QApplication::UnicodeUTF8));
    play_forward_more_action->setShortcut(QApplication::translate("Ui::MainWindow", "PgUp", 0, QApplication::UnicodeUTF8));
    play_backward_more_action->setText(QApplication::translate("Ui::MainWindow", "\353\247\216\354\235\264 \353\222\244\353\241\234", 0, QApplication::UnicodeUTF8));
    play_backward_more_action->setShortcut(QApplication::translate("Ui::MainWindow", "PgDown", 0, QApplication::UnicodeUTF8));
    play_pause_action->setText(QApplication::translate("Ui::MainWindow", "\354\235\274\354\213\234\354\240\225\354\247\200/\354\236\254\354\203\235", 0, QApplication::UnicodeUTF8));
    play_pause_action->setShortcut(QApplication::translate("Ui::MainWindow", "Space", 0, QApplication::UnicodeUTF8));
    file_exit_action->setText(QApplication::translate("Ui::MainWindow", "\354\242\205\353\243\214", 0, QApplication::UnicodeUTF8));
    file_exit_action->setShortcut(QApplication::translate("Ui::MainWindow", "Alt+F4", 0, QApplication::UnicodeUTF8));
    play_stop_action->setText(QApplication::translate("Ui::MainWindow", "\354\240\225\354\247\200", 0, QApplication::UnicodeUTF8));
    play_previous_action->setText(QApplication::translate("Ui::MainWindow", "\354\235\264\354\240\204 \355\214\214\354\235\274", 0, QApplication::UnicodeUTF8));
    play_next_action->setText(QApplication::translate("Ui::MainWindow", "\353\213\244\354\235\214 \355\214\214\354\235\274", 0, QApplication::UnicodeUTF8));
    audio_mute_action->setText(QApplication::translate("Ui::MainWindow", "\354\235\214\354\206\214\352\261\260", 0, QApplication::UnicodeUTF8));
    video_aspect_auto_action->setText(QApplication::translate("Ui::MainWindow", "\354\236\220\353\217\231", 0, QApplication::UnicodeUTF8));
    video_aspect_widget_action->setText(QApplication::translate("Ui::MainWindow", "\354\260\275 \353\271\204\354\234\250", 0, QApplication::UnicodeUTF8));
    video_aspect_4_3_action->setText(QApplication::translate("Ui::MainWindow", "AR 4:3", 0, QApplication::UnicodeUTF8));
    video_aspect_16_9_action->setText(QApplication::translate("Ui::MainWindow", "AR 16:9", 0, QApplication::UnicodeUTF8));
    video_equalizer_action->setText(QApplication::translate("Ui::MainWindow", "\354\235\264\355\200\204\353\235\274\354\235\264\354\240\200", 0, QApplication::UnicodeUTF8));
    play_show_playlist_action->setText(QApplication::translate("Ui::MainWindow", "\354\236\254\354\203\235 \353\252\251\353\241\235", 0, QApplication::UnicodeUTF8));
    play_show_playlist_action->setShortcut(QApplication::translate("Ui::MainWindow", "L", 0, QApplication::UnicodeUTF8));
    subtitle_step_up_action->setText(QApplication::translate("Ui::MainWindow", "\354\236\220\353\247\211 \354\234\204\353\241\234", 0, QApplication::UnicodeUTF8));
    subtitle_step_up_action->setShortcut(QApplication::translate("Ui::MainWindow", "]", 0, QApplication::UnicodeUTF8));
    subtitle_step_down_action->setText(QApplication::translate("Ui::MainWindow", "\354\236\220\353\247\211 \354\225\204\353\236\230\353\241\234", 0, QApplication::UnicodeUTF8));
    subtitle_step_down_action->setShortcut(QApplication::translate("Ui::MainWindow", "[", 0, QApplication::UnicodeUTF8));
    subtitle_add_action->setText(QApplication::translate("Ui::MainWindow", "\354\236\220\353\247\211 \354\266\224\352\260\200", 0, QApplication::UnicodeUTF8));
    subtitle_disable_action->setText(QApplication::translate("Ui::MainWindow", "\354\236\220\353\247\211\354\227\206\354\235\214", 0, QApplication::UnicodeUTF8));
    subtitle_clear_action->setText(QApplication::translate("Ui::MainWindow", "\354\236\220\353\247\211 \353\271\204\354\232\260\352\270\260", 0, QApplication::UnicodeUTF8));
    video_size_100_action->setText(QApplication::translate("Ui::MainWindow", "100%", 0, QApplication::UnicodeUTF8));
    video_size_100_action->setShortcut(QApplication::translate("Ui::MainWindow", "1", 0, QApplication::UnicodeUTF8));
    video_size_200_action->setText(QApplication::translate("Ui::MainWindow", "200%", 0, QApplication::UnicodeUTF8));
    video_size_200_action->setShortcut(QApplication::translate("Ui::MainWindow", "2", 0, QApplication::UnicodeUTF8));
    video_size_50_action->setText(QApplication::translate("Ui::MainWindow", "50%", 0, QApplication::UnicodeUTF8));
    video_size_50_action->setShortcut(QApplication::translate("Ui::MainWindow", "`", 0, QApplication::UnicodeUTF8));
    video_size_300_action->setText(QApplication::translate("Ui::MainWindow", "300%", 0, QApplication::UnicodeUTF8));
    video_size_300_action->setShortcut(QApplication::translate("Ui::MainWindow", "3", 0, QApplication::UnicodeUTF8));
    video_size_400_action->setText(QApplication::translate("Ui::MainWindow", "400%", 0, QApplication::UnicodeUTF8));
    video_size_400_action->setShortcut(QApplication::translate("Ui::MainWindow", "4", 0, QApplication::UnicodeUTF8));
    subtitle_sync_increase_action->setText(QApplication::translate("Ui::MainWindow", "\354\213\261\355\201\254 +0.5\354\264\210", 0, QApplication::UnicodeUTF8));
    subtitle_sync_increase_action->setShortcut(QApplication::translate("Ui::MainWindow", "P", 0, QApplication::UnicodeUTF8));
    subtitle_sync_decrease_action->setText(QApplication::translate("Ui::MainWindow", "\354\213\261\355\201\254 -0.5\354\264\210", 0, QApplication::UnicodeUTF8));
    subtitle_sync_decrease_action->setShortcut(QApplication::translate("Ui::MainWindow", "O", 0, QApplication::UnicodeUTF8));
    subtitle_sync_current_action->setText(QApplication::translate("Ui::MainWindow", "\355\230\204\354\236\254\352\260\222: 0.0\354\264\210", 0, QApplication::UnicodeUTF8));
    option_preferences_action->setText(QApplication::translate("Ui::MainWindow", "\355\231\230\352\262\275\354\204\244\354\240\225", 0, QApplication::UnicodeUTF8));
    video_size_150_action->setText(QApplication::translate("Ui::MainWindow", "150%", 0, QApplication::UnicodeUTF8));
    video_size_250_action->setText(QApplication::translate("Ui::MainWindow", "250%", 0, QApplication::UnicodeUTF8));
    video_size_350_action->setText(QApplication::translate("Ui::MainWindow", "350%", 0, QApplication::UnicodeUTF8));
    video_crop_off_action->setText(QApplication::translate("Ui::MainWindow", "\354\267\250\354\206\214", 0, QApplication::UnicodeUTF8));
    video_crop_4_3_action->setText(QApplication::translate("Ui::MainWindow", "CR 4:3", 0, QApplication::UnicodeUTF8));
    video_crop_16_9_action->setText(QApplication::translate("Ui::MainWindow", "CR 16:9", 0, QApplication::UnicodeUTF8));
    video_size_user_action->setText(QApplication::translate("Ui::MainWindow", "\354\202\254\354\232\251\354\236\220 \354\247\200\354\240\225", 0, QApplication::UnicodeUTF8));
    action_6->setText(QApplication::translate("Ui::MainWindow", "\353\252\251\353\241\235 \353\271\204\354\232\260\352\270\260", 0, QApplication::UnicodeUTF8));
    video_on_top_always_action->setText(QApplication::translate("Ui::MainWindow", "\355\225\255\354\203\201 \353\247\250\354\234\204\353\241\234", 0, QApplication::UnicodeUTF8));
    video_on_top_only_playing_action->setText(QApplication::translate("Ui::MainWindow", "\354\236\254\354\203\235\354\213\234\353\247\214 \353\247\250\354\234\204\353\241\234", 0, QApplication::UnicodeUTF8));
    video_on_top_off_action->setText(QApplication::translate("Ui::MainWindow", "\353\247\250\354\234\204\353\241\234 \353\201\204\352\270\260", 0, QApplication::UnicodeUTF8));
    about_qt_action->setText(QApplication::translate("Ui::MainWindow", "Qt\354\227\220 \353\214\200\355\225\230\354\227\254", 0, QApplication::UnicodeUTF8));
    about_cmp_action->setText(QApplication::translate("Ui::MainWindow", "CMPlayer\354\227\220 \353\214\200\355\225\230\354\227\254", 0, QApplication::UnicodeUTF8));
    play_ab_select_action->setText(QApplication::translate("Ui::MainWindow", "A-B \352\265\254\352\260\204 \354\247\200\354\240\225", 0, QApplication::UnicodeUTF8));
    play_ab_select_action->setShortcut(QApplication::translate("Ui::MainWindow", "R", 0, QApplication::UnicodeUTF8));
    play_ab_advance_action->setText(QApplication::translate("Ui::MainWindow", "\352\263\240\352\270\211 \352\265\254\352\260\204 \353\260\230\353\263\265", 0, QApplication::UnicodeUTF8));
    play_ab_stop_action->setText(QApplication::translate("Ui::MainWindow", "\353\260\230\353\263\265 \354\244\221\354\247\200", 0, QApplication::UnicodeUTF8));
    play_ab_stop_action->setShortcut(QApplication::translate("Ui::MainWindow", "Esc", 0, QApplication::UnicodeUTF8));
    play_forward_much_more_action->setText(QApplication::translate("Ui::MainWindow", "\353\215\224 \353\247\216\354\235\264 \354\225\236\354\234\274\353\241\234", 0, QApplication::UnicodeUTF8));
    play_forward_much_more_action->setShortcut(QApplication::translate("Ui::MainWindow", "Home", 0, QApplication::UnicodeUTF8));
    play_backward_much_more_action->setText(QApplication::translate("Ui::MainWindow", "\353\215\224 \353\247\216\354\235\264 \353\222\244\353\241\234", 0, QApplication::UnicodeUTF8));
    play_backward_much_more_action->setShortcut(QApplication::translate("Ui::MainWindow", "End", 0, QApplication::UnicodeUTF8));
    video_aspect_2_35_1_action->setText(QApplication::translate("Ui::MainWindow", "AR 2.35:1", 0, QApplication::UnicodeUTF8));
    video_crop_2_35_1_action->setText(QApplication::translate("Ui::MainWindow", "CR 2.35:1", 0, QApplication::UnicodeUTF8));
    play_speed_current_action->setText(QApplication::translate("Ui::MainWindow", "\355\230\204\354\236\254: \303\2271 \353\260\260\354\206\215", 0, QApplication::UnicodeUTF8));
    play_speed_increase_action->setText(QApplication::translate("Ui::MainWindow", "+ 0.1 \353\260\260\354\206\215", 0, QApplication::UnicodeUTF8));
    play_speed_increase_action->setShortcut(QApplication::translate("Ui::MainWindow", "+", 0, QApplication::UnicodeUTF8));
    play_speed_decrease_action->setText(QApplication::translate("Ui::MainWindow", "- 0.1 \353\260\260\354\206\215", 0, QApplication::UnicodeUTF8));
    play_speed_decrease_action->setShortcut(QApplication::translate("Ui::MainWindow", "-", 0, QApplication::UnicodeUTF8));
    play_speed_restore_action->setText(QApplication::translate("Ui::MainWindow", "\354\233\220\353\236\230 \354\206\215\353\217\204\353\241\234", 0, QApplication::UnicodeUTF8));
    play_speed_restore_action->setShortcut(QApplication::translate("Ui::MainWindow", "Backspace", 0, QApplication::UnicodeUTF8));
    play_speed_double_action->setText(QApplication::translate("Ui::MainWindow", "\355\230\204\354\236\254\354\235\230 2\353\260\260\354\206\215", 0, QApplication::UnicodeUTF8));
    play_speed_half_action->setText(QApplication::translate("Ui::MainWindow", "\355\230\204\354\236\254\354\235\230 0.5\353\260\260\354\206\215", 0, QApplication::UnicodeUTF8));
    action_2->setText(QApplication::translate("Ui::MainWindow", "\355\214\214\354\235\274", 0, QApplication::UnicodeUTF8));
    open_url_action->setText(QApplication::translate("Ui::MainWindow", "URL", 0, QApplication::UnicodeUTF8));
    open_dvd_action->setText(QApplication::translate("Ui::MainWindow", "DVD", 0, QApplication::UnicodeUTF8));
    recent_clear_action->setText(QApplication::translate("Ui::MainWindow", "\353\252\251\353\241\235\353\271\204\354\232\260\352\270\260", 0, QApplication::UnicodeUTF8));
    action_3->setText(QApplication::translate("Ui::MainWindow", "\343\205\207\343\205\201\343\204\264\343\205\207", 0, QApplication::UnicodeUTF8));
    action1->setText(QApplication::translate("Ui::MainWindow", "1", 0, QApplication::UnicodeUTF8));
    file_menu->setTitle(QApplication::translate("Ui::MainWindow", "\355\214\214\354\235\274(&F)", 0, QApplication::UnicodeUTF8));
    file_open_menu->setTitle(QApplication::translate("Ui::MainWindow", "\354\227\264\352\270\260...", 0, QApplication::UnicodeUTF8));
    open_recent_menu->setTitle(QApplication::translate("Ui::MainWindow", "\354\265\234\352\267\274\354\227\220 \354\236\254\354\203\235\355\225\234 \352\262\203\353\223\244", 0, QApplication::UnicodeUTF8));
    play_menu->setTitle(QApplication::translate("Ui::MainWindow", "\354\236\254\354\203\235(&P)", 0, QApplication::UnicodeUTF8));
    play_ab_menu->setTitle(QApplication::translate("Ui::MainWindow", "A-B \352\265\254\352\260\204 \353\260\230\353\263\265", 0, QApplication::UnicodeUTF8));
    play_speed_menu->setTitle(QApplication::translate("Ui::MainWindow", "\354\236\254\354\203\235 \354\206\215\353\217\204", 0, QApplication::UnicodeUTF8));
    seek_dvd_menu->setTitle(QApplication::translate("Ui::MainWindow", "DVD \355\203\220\354\203\211", 0, QApplication::UnicodeUTF8));
    seek_title_menu->setTitle(QApplication::translate("Ui::MainWindow", "\355\203\200\354\235\264\355\213\200", 0, QApplication::UnicodeUTF8));
    seek_chapter_menu->setTitle(QApplication::translate("Ui::MainWindow", "\354\261\225\355\204\260", 0, QApplication::UnicodeUTF8));
    video_menu->setTitle(QApplication::translate("Ui::MainWindow", "\353\271\204\353\224\224\354\230\244(&V)", 0, QApplication::UnicodeUTF8));
    video_aspect_menu->setTitle(QApplication::translate("Ui::MainWindow", "\354\230\201\354\203\201\353\271\204\354\234\250", 0, QApplication::UnicodeUTF8));
    video_size_menu->setTitle(QApplication::translate("Ui::MainWindow", "\354\230\201\354\203\201\355\201\254\352\270\260", 0, QApplication::UnicodeUTF8));
    video_crop_menu->setTitle(QApplication::translate("Ui::MainWindow", "\354\230\201\354\203\201 \354\236\230\353\235\274\353\202\264\352\270\260", 0, QApplication::UnicodeUTF8));
    video_on_top_menu->setTitle(QApplication::translate("Ui::MainWindow", "\353\247\250\354\234\204\353\241\234", 0, QApplication::UnicodeUTF8));
    audio_menu->setTitle(QApplication::translate("Ui::MainWindow", "\354\230\244\353\224\224\354\230\244(&A)", 0, QApplication::UnicodeUTF8));
    subtitle_menu->setTitle(QApplication::translate("Ui::MainWindow", "\354\236\220\353\247\211(&S)", 0, QApplication::UnicodeUTF8));
    subtitle_select_menu->setTitle(QApplication::translate("Ui::MainWindow", "\354\236\220\353\247\211\354\204\240\355\203\235", 0, QApplication::UnicodeUTF8));
    subtitle_sync_menu->setTitle(QApplication::translate("Ui::MainWindow", "\354\236\220\353\247\211 \353\217\231\352\270\260\355\231\224", 0, QApplication::UnicodeUTF8));
    subtitle_pos_menu->setTitle(QApplication::translate("Ui::MainWindow", "\354\236\220\353\247\211 \354\234\204\354\271\230", 0, QApplication::UnicodeUTF8));
    option_menu->setTitle(QApplication::translate("Ui::MainWindow", "\354\230\265\354\205\230(&O)", 0, QApplication::UnicodeUTF8));
    help_menu->setTitle(QApplication::translate("Ui::MainWindow", "\353\217\204\354\233\200\353\247\220(&H)", 0, QApplication::UnicodeUTF8));
    play_bar->setWindowTitle(QApplication::translate("Ui::MainWindow", "\354\236\254\354\203\235 \353\217\204\352\265\254\353\247\211\353\214\200", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

} // namespace Ui

namespace Ui {
namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui
} // namespace Ui

#endif // UI_MAINWINDOW_H
